export default {
  'Luke Skywalker': '/heroes/luke_skywalker.jpg',
  'C-3PO': '/heroes/c-3po.jpg',
  'R2-D2': '/heroes/r2-d2.jpg',
  'Darth Vader': '/heroes/darth_vader.jpg',
  'Leia Organa': '/heroes/leia_organa.jpg',
  'Owen Lars': '/heroes/owen_lars.jpg',
  'Beru Whitesun lars': '/heroes/beru_whitesun_lars.jpg',
  'R5-D4': '/heroes/r5-d4.jpg',
  'Biggs Darklighter': '/heroes/biggs_darklighter.jpg',
  'Obi-Wan Kenobi': '/heroes/obi-wan_kenobi.jpg',
  'Anakin Skywalker': '/heroes/anakin_skywalker.jpg',
  'Wilhuff Tarkin': '/heroes/wilhuff_tarkin.jpg',
  Chewbacca: '/heroes/chewbacca.jpg',
  'Han Solo': '/heroes/han_solo.jpg',
  Greedo: '/heroes/greedo.jpg',
  'Jabba Desilijic Tiure': '/heroes/jabba_desilijic_tiure.jpg',
  'Wedge Antilles': '/heroes/wedge_antilles.jpg',
  'Jek Tono Porkins': '/heroes/jek_tono_porkins.jpg',
  Yoda: '/heroes/yoda.jpg',
  Palpatine: '/heroes/palpatine.jpg',
  'Boba Fett': '/heroes/boba_fett.jpg',
  'IG-88': '/heroes/ig-88.jpg',
  Bossk: '/heroes/bossk.jpg',
  'Lando Calrissian': '/heroes/lando_calrissian.jpg',
  Lobot: '/heroes/lobot.jpg',
  Ackbar: '/heroes/ackbar.jpg',
  'Mon Mothma': '/heroes/mon_mothma.jpg',
  'Arvel Crynyd': '/heroes/arvel_crynyd.jpg',
  'Wicket Systri Warrick': '/heroes/wicket_systri_warrick.jpg',
  'Nien Nunb': '/heroes/nien_nunb.jpg',
  'Qui-Gon Jinn': '/heroes/qui-gon_jinn.jpg',
  'Nute Gunray': '/heroes/nute_gunray.jpg',
  'Finis Valorum': '/heroes/finis_valorum.jpg',
  'Padmé Amidala': '/heroes/padme_amidala.jpg',
  'Jar Jar Binks': '/heroes/jar_jar_binks.jpg',
  'Roos Tarpals': '/heroes/roos_tarpals.jpg',
  'Rugor Nass': '/heroes/rugor_nass.jpg',
  'Ric Olié': '/heroes/ric_olie.jpg',
  Watto: '/heroes/watto.jpg',
  Sebulba: '/heroes/sebulba.jpg',
  'Shmi Skywalker': '/heroes/shmi_skywalker.jpg',
  'Dud Bolt': '/heroes/dud_bolt.jpg',
  'Quarsh Panaka': '/heroes/quarsh_panaka.jpg',
  Gasgano: '/heroes/gasgano.jpg',
  'Ben Quadinaros': '/heroes/ben_quadinaros.jpg',
  'Ayla Secura': '/heroes/ayla_secura.jpg',
  'Mace Windu': '/heroes/mace_windu.jpg',
  'Ratts Tyerel': '/heroes/ratts_tyerel.jpg',
  'Darth Maul': '/heroes/darth_maul.jpg',
  'Bib Fortuna': '/heroes/bib_fortuna.jpg',
};
